## basic info
site_name: "MaxKB Documentation"
site_url: "https://maxkb.hk"
site_description: "Ready-to-use, flexible RAG Chatbot"
repo_name: "MaxKB"
repo_url: "https://github.com/1Panel-dev/MaxKB"
edit_uri: https://github.com/1Panel-dev/MaxKB-docs
copyright: Copyright &copy; 2025 Lingxia (Hong Kong) Software Co., Limited, All Rights Reserved.

## customization
theme:
  name: "material"
  logo: "img/logo-white.png"
  favicon: "img/facio.ico"
  language: "en"
  palette:
    primary: custom
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css    
markdown_extensions:
  - toc:
      permalink: true
  ## admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  ## content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ## grid
  - attr_list
  - md_in_html      
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1Panel-dev/MaxKB
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/maxkb_ai
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@MaxKB-AI
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Bv7sR3UGZb
  version:
    method: mike
  analytics:
    provider: google
    property: G-C38L48WZ1N

plugins:
  - glightbox

## content nav
nav:
  - Introduction: index.md
  - Get Started:
    - Quick Start: quick_start.md

  #- Tutorials: tutorials.md
  - Development:
    - Building from Source: dev_manual/build_from_source.md
